### ISSUE TITLE
DNS lookup timeout

### ISSUE THREAD

**Issue by jeLee6gi** [dlenski/vpn-slice#45]
I just tried to run vpn-slice for the first time using a single hostname and got the following.

```
WARNING: IPv6 address or netmask set, but this version of vpn-slice has only rudimentary support for them.
WARNING: IPv6 address or netmask set, but this version of vpn-slice has only rudimentary support for them.
Blocked incoming traffic from VPN interface with iptables.
Added routes for 2 nameservers, 0 subnets, 0 aliases.
Restored routes for 0 excluded subnets.
Adding /etc/hosts entries for 2 nameservers...
  xxx.xxx.xxx.xxx = dns0.tun0
  yyy.yyy.yyy.yyy = dns1.tun0
Looking up 1 hosts using VPN DNS servers...
WARNING: Lookup for hostname on VPN DNS servers failed:
	name 'cmd' is not defined
Added hostnames and aliases for 2 addresses to /etc/hosts.
Added 0 routes for named hosts.
Connection setup done, child process 249994 exiting.
```

I think `name 'cmd' is not defined` is unrelated and just a regression from 3a4bbdb, but I still don't know why the lookup times out.

`dig +short hostname` works independently of the VPN connection and returns an IPv4 address and `dig +short @dns0.tun0 hostname` works after connection setup is done.

**Comment by jeLee6gi** [comment]
Quick litte update: I just noticed that it works flawlessly when I run openconnect with `--disable-ipv6`

**Comment by dlenski** [comment]
```
WARNING: Lookup for hostname on VPN DNS servers failed:
	name 'cmd' is not defined
```

Thanks. Fixed in 7c48a662ae1898b003f4a3c00891a6d51e635af4.

Does it work even with IPv6 enabled after this? Per #44, we're trying to figure out whether the IPv6 handling is correct.

**Comment by jeLee6gi** [comment]
Thank you that was helpful, it still fails but now I can see the `dig` command that is timing out.

```
WARNING: Lookup for host.domain.tld on VPN DNS servers failed:
	Command '['/usr/bin/dig', '+short', '+noedns', '-b', 'xxxx:xxxx:xxxx:xxxx::x', '+domain=domain.tld', 'host.domain.tld', 'A', 'host.domain.tld', 'AAAA']' returned non-zero exit status 9.
```

I noticed that the ip address after `-b` is my IPv6 address and the host I am trying to resolve only does IPv4. If I replace the address after `-b` with my IPv4 address, the host can be resolved.

**Comment by dlenski** [comment]
Huh, thanks.

> the ip address after `-b` is my IPv6 address

Right. 

> … and the host I am trying to resolve only does IPv4.

That part is okay. A DNS lookup via IPv6 can lookup IPv4 records (`A`), and vice versa.

Now I can see the problem: your VPN isn't sending any IPv6 addresses of DNS servers (which is perfectly fine), but we are trying to do a lookup via IPv6 anyway. I'll add a patch for this shortly. Please let me know if it enables things to work _without_ disabling IPv6.

**Comment by jeLee6gi** [comment]
That solves my issue, thank you!

**Comment by dlenski** [comment]
Good to know.

I think I really should be replacing the calls to `dig` with a Pythonic DNS library (like https://github.com/rthalley/dnspython, for example)… calling `dig` is getting to be both inefficient and error-prone.
